server:
  port: 7777

spring:
  application:
    name: zuul-gateway-server
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 100MB

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

zuul:
  ignored-services: '*'
  routes:
    auth-server:
      path: /demo/**
      serviceId: PROVIDER-SERVICE

# 上传大文件得将超时时间设置长一些，否则会报超时异常。以下几行超时设置来自http://cloud.spring.io/spring-cloud-static/Camden.SR3/#_uploading_files_through_zuul
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 600000

logging:
  config: classpath:logback.xml



