spring:
  application:
    name: auth-server

server:
  port: 9000
  context-path: /uaa
security:
  sessions: stateless

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka.didispace.com/eureka/

logging:
  config: classpath:logback.xml



